# Generated by Django 3.2.5 on 2021-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210730_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Оценка пользователя'),
        ),
    ]
