# Generated by Django 3.2.5 on 2021-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
