# Generated by Django 3.2.5 on 2021-07-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uploaded',
            new_name='uploated',
        ),
    ]
