# Generated by Django 3.2.5 on 2021-07-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_uploaded_review_uploated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uploated',
            new_name='updated',
        ),
    ]
