# Generated by Django 3.2.5 on 2021-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_uploated_review_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Запись на собитые', 'verbose_name_plural': 'Записи на события'},
        ),
    ]
