# Generated by Django 3.2.5 on 2021-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210907_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('u', 'user'), ('m', 'manager')], default='u', max_length=1, null=True, verbose_name='Роль'),
        ),
    ]
