# Generated by Django 3.2.5 on 2021-09-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_to_private_events',
            field=models.BooleanField(default=False, verbose_name='Доступ к приватным событиям'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('u', 'user'), ('m', 'manager'), ('a', 'admin')], default='u', max_length=1, verbose_name='Роль'),
        ),
    ]
